#pragma once
#ifndef __ELOG_H__
#define __ELOG_H__

#include "framework.h"

#define 红色 FOREGROUND_RED|FOREGROUND_INTENSITY
#define 绿色 FOREGROUND_GREEN|FOREGROUND_INTENSITY
#define 蓝色 FOREGROUND_BLUE|FOREGROUND_INTENSITY
#define 青色 FOREGROUND_GREEN|FOREGROUND_BLUE|FOREGROUND_INTENSITY
#define 粉色 FOREGROUND_RED|FOREGROUND_BLUE|FOREGROUND_INTENSITY
#define 黄色 FOREGROUND_RED|FOREGROUND_GREEN|FOREGROUND_INTENSITY
#define 白色 FOREGROUND_RED|FOREGROUND_GREEN|FOREGROUND_BLUE|FOREGROUND_INTENSITY
#define 灰色 FOREGROUND_INTENSITY

#endif